### ISSUE TITLE
Add a license to the repository

### ISSUE THREAD

**Issue by cbjuan** [lupodevelop/wanna-fortune-teller#1]
I recently came across your project wanna-fortune-teller and I noticed that the repository github.com/lupodevelop/wanna-fortune-teller currently does not have a license specified.

Why Adding a License is Important?

As [GitHub documents](https://docs.github.com/en/repositories/managing-your-repositorys-settings-and-features/customizing-your-repository/licensing-a-repository)
>Public repositories on GitHub are often used to share open source software. For your repository to truly be open source, you'll need to license it so that others are free to use, change, and distribute the software.

Would be possible to add a valid license to this repository? Probably something really OpenSource such as the [Apache 2.0 license](https://www.apache.org/licenses/LICENSE-2.0) would fit really well.

Thanks!

**Comment by lupodevelop** [comment]
Hello @cbjuan, Thanks for this issue, I had never thought about the inserting a license... Just like I never thought anyone would find this silly experiment here on GitHub  😉. 

Anyway I took your advice into consideration and applied the **Apache license** in this commit [5798a46](https://github.com/lupodevelop/wanna-fortune-teller/commit/5798a46fb2826aa315537dd7fd8c2fbe278fcead)

It's been a pleasure to get feedback from you and I admit I've invested some time on both **LinkedIn** and your publications. 

How did you find this particular project?

*However if you win the lottery with this bizarre experiment a donation would be appreciated*😉

**Comment by cbjuan** [comment]
I found it via GH search

Thank you!
